### ISSUE TITLE
Review semver-minor backports

### ISSUE THREAD

**Issue by gibfahn** [nodejs/Release#228]
I know it's a bit early, but it's probably worth starting to accumulate the list of PRs for which a backport to Node 6 has been requested (as the first one has been requested).

- Previous Issue: https://github.com/nodejs/LTS/issues/188
- Command: `branch-diff --reverse --filter-release --require-label=semver-minor --exclude-label=semver-major,meta,dont-land-on-v6.x,backport-requested-to-v6.x up/v6.x up/v8.x`

### Unsorted

- [x] **http:** overridable keep-alive behavior of `Agent` [#13005](https://github.com/nodejs/node/pull/13005)
- [x] **src:** allow CLI args in env with NODE_OPTIONS [#12677](https://github.com/nodejs/node/pull/12677)
- [x] **assert.fail()** accept a single argument or two arguments [#12293](https://github.com/nodejs/node/pull/12293)
- [ ] [[`1ee38eb874`](https://github.com/nodejs/node/commit/1ee38eb874)] - **(SEMVER-MINOR)** **util**: add %i and %f formatting specifiers (    Roman Reiss) [#10308](https://github.com/nodejs/node/pull/10308)
- [ ] [[`75f4329e01`](https://github.com/nodejs/node/commit/75f4329e01)] - **(SEMVER-MINOR)** **crypto**: add randomFill and randomFillSync (    Evan Lucas) [#10209](https://github.com/nodejs/node/pull/10209)
- [ ] [[`4fb27d43f0`](https://github.com/nodejs/node/commit/4fb27d43f0)] - **intl**: Add more versions from ICU (    Steven R. Loomis) https://github.com/nodejs/node/pull/9266
- [x]  **crypto:** add sign/verify support for RSASSA-PSS [#11705](https://github.com/nodejs/node/pull/11705)
- [x] **inspector:** enable --inspect-brk in v6 [#12615](https://github.com/nodejs/node/pull/12615)

### Manual

**Comment by sam-github** [comment]
What about https://github.com/nodejs/node/pull/12677#issuecomment-304870791 ?

**Comment by gibfahn** [comment]
>What about nodejs/node#12677 (comment) ?

Yep, added.

This is a collaborative list, so if you want to add stuff just do it. These are just semver-minors we should look at, no consensus is necessary to add one to the list.

**Comment by refack** [comment]
Backported by mistake, so for your consideration: https://github.com/nodejs/node/pull/14427

**Comment by srl295** [comment]
add more ICU  versions - yes, this would be good

**Comment by MylesBorins** [comment]
There are a bunch of semver-minor ones that are labelled lts-watch

https://github.com/nodejs/node/pulls?q=is%3Apr+label%3Alts-watch-v6.x+label%3Asemver-minor+is%3Aclosed

and a bunch that have backports already in

https://github.com/nodejs/node/pulls?utf8=%E2%9C%93&q=is%3Aopen%20is%3Apr%20label%3Av6.x%20

**Comment by Fishrock123** [comment]
We (NodeSource) would like to have access to `process.ppid` in LTS branches - https://github.com/nodejs/node/pull/16839

It requires a libuv upgrade, so we will have to see if that is feasible. If not, I imagine the backport of that particular feature would not be overly complex.

**Comment by cjihrig** [comment]
FWIW, the libuv 1.x release line should continue to be backport-able.

**Comment by MylesBorins** [comment]
@Fishrock123 which version of libuv? We updated v6.x and v8.x to 1.15.0 in the last minor

There is room for a minor on 6.x and 8.x in February if we want to do it... I would say this isn't likely to land on 4.x though

**Comment by Fishrock123** [comment]
From the PR:

> depends on the libuv 1.16.0 update
