### ISSUE TITLE
UlisesGascon onboarding

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/Release#892]
* [x] Be added to the GitHub [releasers team](https://github.com/orgs/nodejs/teams/releasers) in the Node.js org (grants ci-release access)
* [x] Be added to the GitHub [security-release team](https://github.com/orgs/nodejs/teams/security-release) in the Node.js and nodejs-private orgs
* [x] Have a single, high quality SSH key added to the "dist" user on the primary www server (see below for guidelines regarding SSH key quality)
* [x] Open a PR to add their GPG key to the nodejs/node [README.md](https://github.com/nodejs/node/#release-keys): nodejs/node#49196
  * [x] Once landed, the key should be cherry-picked to all active release staging branches (i.e. the active `vMM.x-staging` branches).
  * [x] Any future updates to the key should also be cherry-picked to all active release staging branches.
* [x] Open a PR in [nodejs/docker-node](https://github.com/nodejs/docker-node/) to add their GPG key to [node.keys](https://github.com/nodejs/docker-node/blob/main/keys/node.keys): nodejs/docker-node#1953
* [x] Open a PR in [nodejs/release-keys](https://github.com/nodejs/release-keys) to add their GPG key via `./cli.sh add $KEY_ID`: nodejs/release-keys#25.
* [x] Open a PR in [nodejs/Release](https://github.com/nodejs/Release) to add themself under the "Releasers team" heading via `ncu-team sync README.md`: https://github.com/nodejs/Release/pull/939
* [x] Add them to the `#nodejs-release-private` team on the OpenJS Slack.

cc: @UlisesGascon

**Comment by RafaelGSS** [comment]
@richardlau I assume Ulises already has access to ci-release since he's member of nodejs/build, right?

**Comment by RafaelGSS** [comment]
For the keys, let's wait the v20.6.0 to go out before merging your keys.

**Comment by RafaelGSS** [comment]
@UlisesGascon can you open a PR to add you to the Release team?

**Comment by UlisesGascon** [comment]
> @UlisesGascon can you open a PR to add you to the Release team?

Yes, here is the PR: https://github.com/nodejs/Release/pull/939. 

I think only one thing is missing, can you add me to the [security-release team](https://github.com/orgs/nodejs/teams/security-release)?

**Comment by RafaelGSS** [comment]
Concluded!
